tags:
    name: File Server
    description: The file server

/img/{img}:
    get:
        summary: Get the image using filename
        tags: [File Server]
        security:
            - bearerAuth: []
        parameters:
            - in: path
              name: img
              type: string
              example: 456454.jpg
        responses:
            "401":
                content:
                    text/plain:
                        schema:
                            type: string
                            example: "Unauthorized"
            "404":
                content:
                    text/plain:
                        schema:
                            type: string
                            example: Not Found
            "200":
                content:
                    image/*:
                        schema:
                            type: string
                            format: binary
/img:
    post:
        summary: Upload image(s) to server
        description: Only admins can upload the images
        tags: [File Server]
        security:
            - bearerAuth: []
        requestBody:
            required: true
            content:
                multipart/form-data:
                    schema:
                        type: object
                        required:
                            - images
                        properties:
                            images:
                                type: array
                                items:
                                    type: string
                                    format: binary
                                minItems: 1
        responses:
            "401":
                content:
                    text/plain:
                        schema:
                            type: string
                            example: "Unauthorized"
            "403":
                content:
                    text/plain:
                        schema:
                            type: string
                            example: "Forbidden"
            "500":
                content:
                    text/plain:
                        schema:
                            type: string
                            example: Internal Server Error
            "200":
                content:
                    application/json:
                        schema:
                            oneOf:
                                - $ref: "#/components/schemas/fileServerResponse"
                                - type: array
                                  items:
                                      $ref: "#/components/schemas/fileServerResponse"
