tags:
    name: Payment
    description: Process the order payment

/pay/config:
    get:
        summary: Get Stripe config info
        tags: [Payment]
        security:
            - bearerAuth: []
        responses:
            "401":
                content:
                    text/plain:
                        schema:
                            type: string
                            example: "Unauthorized"
            "200":
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                PUBLISH_KEY:
                                    type: string
                                    example: 8093risfjsiouffpaodiiap
            "417":
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                PUBLISH_KEY:
                                    type: string
                                    example: N/A
/pay/create-intent:
    post:
        summary: Create the payment intent and return client secret
        tags: [Payment]
        security:
            - bearerAuth: []
        requestBody:
            required: true
            content:
                application/json:
                    schema:
                        type: object
                        required:
                            - orderItems
                        properties:
                            orderItems:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        productTitle:
                                            type: string
                                        productCount:
                                            type: number
                                            format: integer
                                        unitCost:
                                            type: number
                                            format: integer
                                    required:
                                        - productTitle
                                        - productCount
                                        - unitCost
                                    example:
                                        productTitle: Carrots
                                        productCount: 40
                                        unitCost: 60
                                    minItems: 1
        responses:
            "401":
                content:
                    text/plain:
                        schema:
                            type: string
                            example: "Unauthorized"
            "400":
                description: Invalid parameters
                content:
                    text/plain:
                        schema:
                            type: string
                            example: orderItems (supposed to be in body) is required
            "417":
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                done:
                                    type: boolean
                                    example: false
                                message:
                                    type: string
                                    example: No such product exists
            "201":
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                done:
                                    type: boolean
                                    example: true
                                message:
                                    type: string
                                    example: Client Secret

/pay/finalize:
    post:
        summary: Finalize the payment
        tags: [Payment]
        security:
            - bearerAuth: []
        requestBody:
            required: true
            content:
                application/json:
                    schema:
                        type: object
                        required:
                            - capture
                            - clientSecret
                        properties:
                            capture:
                                type: boolean
                                description: true for capture and false to cancel
                                example: true
                            clientSecret:
                                type: string
                                example: pi_3Pjkf5RvSZigFhCP1h2c9LVu_jufpajfska
        responses:
            "401":
                content:
                    text/plain:
                        schema:
                            type: string
                            example: "Unauthorized"
            "400":
                description: Invalid parameters
                content:
                    text/plain:
                        schema:
                            type: string
                            example: orderItems (supposed to be in body) is required
            "417":
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                done:
                                    type: boolean
                                    example: false
                                message:
                                    type: string
                                    example: No such product exists
            "201":
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                done:
                                    type: boolean
                                    example: true
                                message:
                                    type: string
                                    example: Client Secret
