/pay:
    post:
        summary: Checkout after some shopping
        tags: [Products]
        security:
            - bearerAuth: []
        requestBody:
            required: true
            content:
                application/json:
                    schema:
                        type: object
                        required:
                            - grandTotal
                            - paymentAccountInfo
                            - orderItems
                        properties:
                            orderItems:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        productTitle:
                                            type: string
                                        productCount:
                                            type: number
                                            format: integer
                                        unitCost:
                                            type: number
                                            format: integer
                                    required:
                                        - productTitle
                                        - productCount
                                        - unitCost
                                    example:
                                        productTitle: Carrots
                                        productCount: 40
                                        unitCost: 60
                            grandTotal:
                                type: number
                                format: integer
                                example: 54000
                            shippingFee:
                                type: number
                                format: integer
                            discounted:
                                type: number
                                format: integer
                            convienceFee:
                                type: number
                                format: integer
                            paymentAccountInfo:
                                type: object
                                required:
                                    - accountType
                                    - ID
                                properties:
                                    accountType:
                                        type: string
                                        enum: [Visa, Master, Amex, PayPal]
                                    ID:
                                        type: string
                                    legalName:
                                        type: string
                                    expiry:
                                        type: string
                                    cvv:
                                        type: number
                                        format: integer
                                example:
                                    accountType: Visa
                                    ID: 5464 4646 45646 466
                                    legalName: SaadUllah
                                    expiry: 07/27
                                    cvv: 1234
        responses:
            "401":
                content:
                    text/plain:
                        schema:
                            type: string
                            example: "Unauthorized"
            "400":
                description: Invalid parameters
                content:
                    text/plain:
                        schema:
                            type: string
                            example: grandTotal (supposed to be in body) is required
            "417":
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                done:
                                    type: boolean
                                    example: false
                                message:
                                    type: string
                                    example: No such product exists
            "201":
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                done:
                                    type: boolean
                                    example: true
                                message:
                                    type: string
                                    example: Transaction ID
